# Generated by Django 5.0.4 on 2024-04-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_careerinformations_register_subscribe_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerInformations',
            new_name='CareerInformation',
        ),
    ]
