# Generated by Django 5.0.4 on 2024-04-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_courseplaylist_mentor_payment_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='category',
        ),
    ]
