# Generated by Django 5.0.4 on 2024-04-22 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
