# Generated by Django 5.0.4 on 2024-04-22 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
