# Generated by Django 5.0.4 on 2024-04-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_descriptio_mentor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rating',
            new_name='raiting',
        ),
    ]
